# Pre-commit フック設定
# 基本的な品質チェックをコミット前に実行

repos:
  # Python フォーマッター
  - repo: https://github.com/psf/black
    rev: '24.10.0'
    hooks:
      - id: black
        language_version: python3

  # Python リンター
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8

  # Python 型チェック
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ['lambapi/', '--exclude', 'lambapi/templates/']
        pass_filenames: false

  # セキュリティチェック
  - repo: https://github.com/pycqa/bandit
    rev: '1.7.10'
    hooks:
      - id: bandit
        args: ['--skip', 'B101']

  # テスト実行
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        args: ['-x', '--tb=short']
        pass_filenames: false
        always_run: true
