name: 🐛 バグ報告
description: バグや問題を報告
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        🐛 バグ報告をお聞かせください。問題の詳細を教えてください。

  - type: textarea
    id: bug-description
    attributes:
      label: バグの説明
      description: 発生している問題について明確で簡潔に説明してください。
      placeholder: "...のエラーが発生します"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: バグを再現するための手順を教えてください。
      placeholder: |
        1. '...' に移動
        2. '...' をクリック
        3. '...' まで下にスクロール
        4. エラーを確認
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 本来どのような動作をするべきかを教えてください。
      placeholder: "...のように動作するはずです"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作
      description: 実際にはどのような動作をしているかを教えてください。
      placeholder: "実際には...のようになります"
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: エラーログ・スタックトレース
      description: エラーメッセージやスタックトレースがあれば貼り付けてください。
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File "...", line ..., in ...
            ...
        Error: ...

  - type: textarea
    id: code-sample
    attributes:
      label: 最小再現コード
      description: 問題を再現できる最小限のコードサンプルを提供してください。
      render: python
      placeholder: |
        from lambapi import API
        
        def create_app(event, context):
            app = API(event, context)
            
            @app.get("/test")
            def test():
                # ここで問題が発生
                return {"message": "test"}
            
            return app

  - type: input
    id: lambapi-version
    attributes:
      label: lambapi バージョン
      description: 使用している lambapi のバージョンを教えてください。
      placeholder: "例: 0.1.1"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python バージョン
      description: 使用している Python のバージョンを教えてください。
      placeholder: "例: 3.11.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 実行環境
      description: どの環境で問題が発生していますか？
      options:
        - "AWS Lambda"
        - "ローカル開発環境"
        - "その他"
    validations:
      required: true

  - type: textarea
    id: environment-details
    attributes:
      label: 環境の詳細
      description: OS、AWS Lambda ランタイム、その他の環境情報を教えてください。
      placeholder: |
        - OS: macOS 13.0
        - AWS Lambda Runtime: python3.11
        - リージョン: us-east-1

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: その他、問題の解決に役立つ情報があれば教えてください。

  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      options:
        - label: 既存の issue で同様の問題が報告されていないことを確認しました
          required: true
        - label: 最新バージョンで問題が再現することを確認しました
          required: true
        - label: ドキュメントで解決方法を探しましたが見つかりませんでした
          required: true