AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: lambapi CRUD API アプリケーション

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    Environment:
      Variables:
        ENVIRONMENT: production

Resources:
  lambapiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref lambapiApi

  lambapiApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${lambapiApi}.execute-api.${AWS::Region}.amazonaws.com/prod"